#!/bin/bash

ID=`python -c 'from config import *; print uid'`

# presuming that you're on a single-user system,
#  you won't need to run this pkill as root
pkill firefox-bin
pwd > ~/.mozilla/firefox/*.default/extensions/{$ID}
firefox &

